services:
  web:
    mem_limit: 256m
    image: ${APP_IMAGE:-ghcr.io/danielmoessner/books.danielmoessner.de:latest}
    restart: unless-stopped
    user: "999:33"
    env_file:
      - ${APP_ENV_FILE:-/home/books.danielmoessner.de/books.env}
    environment:
      PHX_SERVER: "true"
      PHX_HOST: ${PHX_HOST:-books.danielmoessner.de}
      PORT: "4000"
      SQLITE_DB_PATH: "/data/prod.sqlite3"
    ports:
      - "${APP_BIND_IP:-127.0.0.1}:${APP_PORT:-8060}:4000"
    command: /app/_build/prod/rel/books/bin/books start
    volumes:
      - ${APP_SQLITE_PATH:-/home/books.danielmoessner.de/books.sqlite3}:/data/prod.sqlite3