app_remote_dir: /home/books.danielmoessner.de

app_sqlite_host_path: "{{ app_remote_dir }}/books.sqlite3"

app_env_file: "{{ app_remote_dir }}/books.env"

app_bind_ip: 127.0.0.1

app_port: 8060

app_domain: books.danielmoessner.de

app_nginx_site_name: books.danielmoessner.de

app_client_max_body_size: 50m

app_domain_aliases: []

app_certbot_webroot: /var/www/certbot

app_image_repo: ghcr.io/danielmoessner/books.danielmoessner.de
